# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b30c09f36fd9a0f3a5116de11548beff0456d47c0e1ec9495831c229292cff525e833bc01221c31fb6c90a2b7f928ab94aab5c8b5a7ef0639d9940333c866da7

test:
  secret_key_base: 7041accd3498088f08c5b9e704d59824a10247bde131dce7337a9ba6ea3876bbeefe9a3ae97be6a8b1daaa37f97be1de2241107116d3e995522554fd9e956969

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
